### PR TITLE
Bug fixes for/update of "Changes in cloud/radiation interaction in GSD physics suite", bug fixes for non-aerosol-aware Thompson MP

### LINKED ISSUE #10: Thompson MP: rain number concentration not implemented/used in all routines.
Thompson MP uses the following tracers:
```
FIELD_TABLE -> TRACER_ARRAY
sphum       -> qgrs(i,k,ntqv) 
liq_wat     -> qgrs(i,k,ntcw) 
ice_wat     -> qgrs(i,k,ntiw) 
rainwat     -> qgrs(i,k,ntrw) 
snowwat     -> qgrs(i,k,ntsw) 
graupel     -> qgrs(i,k,ntgl)
water_nc    -> qgrs(i,k,ntlnc) # only if is_aerosol_aware = .true.
ice_nc      -> qgrs(i,k,ntinc)
rain_nc     -> qgrs(i,k,ntrnc)
o3mr        -> qgrs(i,k,ntoz) 
liq_aero    -> qgrs(i,k,ntwa)  # only if is_aerosol_aware = .true. 
ice_aero    -> qgrs(i,k,ntia)  # only if is_aerosol_aware = .true.
```
However, not all the GFS interstitial code seems to be correct, mainly because the previous implementation of the 2012 Thompson scheme in IPD lumped certain tracers together. For instance, from GFS_PBL_generic_pre_run:
```
        vdftra(i,k,1)  = qgrs(i,k,ntqv)
        vdftra(i,k,2)  = qgrs(i,k,ntcw)
        vdftra(i,k,3)  = qgrs(i,k,ntiw)
        vdftra(i,k,4)  = qgrs(i,k,ntrw)
        vdftra(i,k,5)  = qgrs(i,k,ntsw)
        MISSING        = qgrs(i,k,ntgl)
        vdftra(i,k,6)  = qgrs(i,k,ntlnc)
        vdftra(i,k,7)  = qgrs(i,k,ntinc)
        MISSING        = qgrs(i,k,ntrnc)
        vdftra(i,k,8)  = qgrs(i,k,ntoz)
        vdftra(i,k,9)  = qgrs(i,k,ntwa)
        vdftra(i,k,10) = qgrs(i,k,ntia)
```

### PR DESCRIPTION
**Pull request by climbfuji**
This PR:
- contains the original PR from @tanyasmirnova for "Changes in cloud/radiation interaction in GSD physics suite", https://github.com/NOAA-GSD/ccpp-physics/pull/12
- adds missing tracers to array of diffused tracers for Thompson MP (fixes https://github.com/NOAA-GSD/ccpp-physics/issues/10)
- fixes several bugs related for the non-aerosol-aware Thompson microphysics option
- removes the `mynnrad_{pre,post}` schemes (superseded by `sgscloud_{pre,post}`)

Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/16
https://github.com/NOAA-GSD/fv3atm/pull/13
https://github.com/NOAA-GSD/ufs-weather-model/pull/11

See https://github.com/NOAA-GSD/ufs-weather-model/pull/11 for regression testing information.

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]
Dom,
Thank you very much for fixing all the bugs in this PR.
Tanya

**Comment by climbfuji** [comment]
Thanks for looking at the changes! I am not going to merge them now. Instead, I would like to ask @hannahcbarnes and/or @haiqinli to check out this code and run our usual set of 10 test cases for comparison against our baseline:
`
git clone -b gsd-dev-clouds_thompson-no-aero_dom --recursive https://github.com/climbfuji/ufs-weather-model
`
Thanks very much in advance!

**Comment by haiqinli** [comment]
@climbfuji Sure, we will do the retro runs and verification. Thanks.

**Comment by climbfuji** [comment]
Thanks, @haiqinli !

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
