### PR TITLE
radar_tten support, merged for the seventh time

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
Merges the old RAP/HRRR radar-tten support, for the seventh time. This is not sufficiently tested yet.

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
@grantfirl @ligiabernardet heads up about a PR that introduces several new standard names for radar tendencies. This code will first go in to gsl/develop but eventually come to NCAR ccpp-physics main. Do you want to provide feedback on the newly suggested standard names?

@SamuelTrahanNOAA you may want to look at https://github.com/ESCOMP/CCPPStandardNames/blob/main/StandardNamesRules.rst for the new/updated rules on how to compose new CCPP standard names.

**Comment by SamuelTrahanNOAA** [comment]
The new variable is a bizarrely-specific one that almost certainly doesn't exist in any standards. The data assimilation produces prescribed microphysics temperature tendencies from radar data. The radar_tten code in ccpp replaces the microphysics tendency with the prescribed tendency for a half hour or so, where the data is available. Historically, the variable in WRF has been called dfi_radar_tten, for obvious reasons.

**Comment by DomHeinzeller** [comment]
> The new variable is a bizarrely-specific one that almost certainly doesn't exist in any standards. The data assimilation produces prescribed microphysics temperature tendencies from radar data. The radar_tten code in ccpp replaces the microphysics tendency with the prescribed tendency for a half hour or so, where the data is available. Historically, the variable in WRF has been called dfi_radar_tten, for obvious reasons.

I still think that the standard name rules provide some guidance for composing these new standard names. For example:
```
[dfi_radar_tten]
  standard_name = dfi_radar_tten
  long_name = prescribed microphysics temperature tendency from radar data
  units = K s-1
  dimensions = (horizontal_loop_extent,vertical_layer_dimension,num_dfi_radar)
  type = real
  kind = kind_phys
  intent = in
  optional = F
```
I think (but I am not the expert) that a suitable standard name that follows the rules would be
```
  standard_name = tendency_of_temperature_for_microphysics_due_to_radar_data
```
or maybe
```
  standard_name = tendency_of_temperature_for_microphysics_due_to_radar_data_assimilation
```
but I would prefer to hear from Grant or Ligia.

**Comment by hu5970** [comment]
@SamuelTrahanNOAA I have tested this PR and it works as expected. Please trying to merge this to develop and authoritative repository.

**Comment by SamuelTrahanNOAA** [comment]
This PR is out of date. I will close it and open a new one for the latest branch.

**Pull request closed without merging**
