### PR TITLE
GF_Tune_Oct2021

### PR DESCRIPTION
**Pull request by hannahcbarnes**
- Aerosol-awareness in GF is turned back on
- clwdet (cloud-water detrainment) is tuned
- evfact (evaporation fraction) and tun_rad_deep, tun_rad_mid (radiation factors) are made scale-aware

### CODE REVIEW

**Comment by hannahcbarnes** [comment]
I am working on trying to run the regression tests right now. However, I have not run the entire set before. I hope to have it run soon.

**Review by DomHeinzeller — COMMENTED** [review]
The changes look good to the extent that I understand them. Will run the regression tests on Hera with Intel and GNU now.

**Comment by hannahcbarnes** [comment]
Thanks Dom.

I tried to run the regression tests myself last week, but it was going really slow for me.

**Comment by DomHeinzeller** [comment]
Associated PRs:

https://github.com/NOAA-GSL/ccpp-physics/pull/108
https://github.com/NOAA-GSL/fv3atm/pull/110
https://github.com/NOAA-GSL/ufs-weather-model/pull/104

**Comment by DomHeinzeller** [comment]
For regression testing, see https://github.com/NOAA-GSL/ufs-weather-model/pull/104.

**Review by DomHeinzeller — APPROVED** [review]

**Comment by hannahcbarnes** [comment]
Thanks Dom! So glad this went better this time around.

**Pull request merged**
