### PR TITLE
Merge gsl/develop to RRFS_dev

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
See title for details.

There are conflicts where code was commented out, but that code changed.

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
There are conflicts where code was commented out, but that code changed.

**Comment by SamuelTrahanNOAA** [comment]
Developer @mdtoyNOAA made the conflicting changes in RRFS_dev, and he's gone this week. He commented out some code, and the code he commented out has changed in gsl/develop. I'm pretty sure we can resolve the conflicts by commenting out the new code. It looks like that will achieve his intended effect. Does anyone object?

**Comment by SamuelTrahanNOAA** [comment]
> Developer @mdtoyNOAA made the conflicting changes in RRFS_dev, and he's gone this week. He commented out some code, and the code he commented out has changed in gsl/develop. I'm pretty sure we can resolve the conflicts by commenting out the new code. It looks like that will achieve his intended effect. Does anyone object?

I'm hoping for a response from @tanyasmirnova or @joeolson42 here.

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA It is ok with me to comment out the new code.

**Comment by joeolson42** [comment]
It's OK with me too.

**Comment by SamuelTrahanNOAA** [comment]
I'm going to generate new baselines before merging this.

**Comment by SamuelTrahanNOAA** [comment]
I'm going to have to make a branch for this merge due to the regression test logs. I'll open another PR shortly.

**Pull request closed without merging**
