### PR TITLE
New codeowners for NOAA-GSL repo

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
This updates the list of people who will be automatically asked for a review when there's a ccpp/physics PR in the NOAA-GSL repository. It only affects ccpp/physics, not the other repositories.

This PR cannot be merged until the repository settings are updated.

### CODE REVIEW

**Review by hannahcbarnes — APPROVED** [review]

**Review by haiqinli — APPROVED** [review]

**Review by tanyasmirnova — APPROVED** [review]

**Review by joeolson42 — APPROVED** [review]

**Review by mdtoyNOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
We're removing Dom from the codeowners list since he no longer maintains the gsl/develop branch. He's still in the NCAR main branch of course; this PR is only to GSL repositories.

**Review by zhanglikate — APPROVED** [review]

**Review by christinaholtNOAA — APPROVED** [review]

**Review by hu5970 — APPROVED** [review]

**Comment by climbfuji** [comment]
@SamuelTrahanNOAA thanks for doing this. While looking at the changes I noticed the github banner saying that this CODEOWNERS file contains "errors" - basically it complains about everyone listed who is not a member of the NOAA-GSL organization I believe.

Screen Shot 2022-03-09 at 6 30 43 PM

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA thanks for doing this. While looking at the changes I noticed the github banner saying that this CODEOWNERS file contains "errors" - basically it complains about everyone listed who is not a member of the NOAA-GSL organization I believe.

They are all members of NOAA-GSL, but they don't have write access. That's why the PR description says the repository settings have to be updated before this is merged.

**Comment by climbfuji** [comment]
> > @SamuelTrahanNOAA thanks for doing this. While looking at the changes I noticed the github banner saying that this CODEOWNERS file contains "errors" - basically it complains about everyone listed who is not a member of the NOAA-GSL organization I believe.
> 
> They are all members of NOAA-GSL, but they don't have write access. That's why the PR description says the repository settings have to be updated before this is merged.

Ok, thanks.

**Pull request merged**
