### PR TITLE
bug fixes in ugwp and gsl drag suites

### PR DESCRIPTION
**Pull request by mdtoy**
This PR fixes 3 bugs in the ugwpv1/gsl drag suites:

1)  drag_suite.F90:  The modifications fix a failure to pass "decomposition change" regression tests.  The "scale aware" variables "ls_taper" and "ss_taper" had been scalars based on the grid size at position "i=1" of the block, therefore, the results changed for each change in decomposition.  Instead these variables are now 1D vectors that take into account the grid size at each grid point.  There are other associated variables that changed from 1D vectors to 2D vectors as a result of the change, e.g., dxy4 and dxy4p.  There were significant changes in loop structures as a result of this fix.

2) cires_ugwpv1_oro.F90:  The calculation of the final u and v tendencies had been mixed up.  This simple bug fix corrects the issue.

3)  ugwpv1_gsldrag.F90:  This fixes a logic error associated with the "do_ugwp" namelist switches.

The mods were regression-tested and the log file is on Hera at:
/scratch1/BMC/wrfruc/mtoy/git_local/ufs-weather-model.gsl_develop/tests/RegressionTests_hera.intel.m.log

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
@mdtoy Didn't we already merge this into the authoritative repositories?

**Comment by mdtoy** [comment]
Yes, but it didn’t seem to make it into the NOAA-GSL repo.

**Comment by climbfuji** [comment]
> Yes, but it didn’t seem to make it into the NOAA-GSL repo.
> […](#)

Are these commits cherry-picked from the authoritative repositories?

**Comment by mdtoy** [comment]
No.  I made a series of bug fixes in the ufs-weather-community/ufs-weather-model repo, which links to the NCAR/ccpp-physics repo over the past 6 months or so.  It looked like the older bug fixes made it into the NOAA-GSL repo, but not these last three that I just submitted.  The fix to drag_suite.F90 is the big one that fixed the “decomposition change” reproducibility.

**Comment by DomHeinzeller** [comment]
I am afraid we can't merge this. It will lead to lots of merge conflicts once we update gsl/develop from the authoritative repositories. There are two ways to do this:
1. Cherry pick the original commits to the authoritative repositories (if possible)
2. Update gsl/develop from the authoritative repositories

The latter is obviously preferred, because it will have to happen anyway sooner or later, and the former would just be an unnecessary duplication of efforts.

I started the update already, see the following draft PRs:

https://github.com/NOAA-GSL/fv3atm/pull/111
https://github.com/NOAA-GSL/ccpp-framework/pull/19
https://github.com/NOAA-GSL/ccpp-physics/pull/109
https://github.com/NOAA-GSL/ufs-weather-model/pull/105

I expect these to go in immediately after Hannah's GF tuning PRs are merged.

**Comment by mdtoy** [comment]
I thought I merged my bug fixes into the “top of the trunk” of the NOAA-GSL repo.  When I issued the PR and set up the base repo settings, it said that the merges could be made.

**Comment by climbfuji** [comment]
The point is that we need the *original* commits (hashes), not manual changes that are new commits hashes.

**Comment by DomHeinzeller** [comment]
Also, this PR won't be needed as soon as the PRs that I listed above are merged.

**Comment by mdtoy** [comment]
By “original” commits, do you mean the commits I made in the NCAR/ccpp-physics repo (and that were merged)?  It seems like that would be more of a spaghetti mess then the small manual deltas I made within the NOAA-GSL/ccpp-physics repo.

**Comment by climbfuji** [comment]
> By “original” commits, do you mean the commits I made in the NCAR/ccpp-physics repo (and that were merged)? It seems like that would be more of a spaghetti mess then the small manual deltas I made within the NOAA-GSL/ccpp-physics repo.
> […](#)

It won't be straightforward unless these commits were a few small and clean commits that only did what you are trying to do here. But again, we cannot merge new commits and then manually resolve all merge conflicts later. That is not how things work with git.

**Comment by mdtoy** [comment]
Does it help that the three ccpp-physics files that are affected by this PR:
drag_suite.F90,
cires_ugwpv1_oro.F90,
and ugwpv1_gsldrag.F90
are identical to the ones in the NCAR/ccpp-physics repo?  What I did, actually now that I remember, was just to copy them over from NCAR/ccpp-physics to my branch of NOAA-GSL/ccpp-physics.  So effectively, they are already “merged" into the authoritative repository.  Am I getting this right?  If not, I’ll cry uncle.  :)

**Comment by climbfuji** [comment]
> Does it help that the three ccpp-physics files that are affected by this PR: drag_suite.F90, cires_ugwpv1_oro.F90, and ugwpv1_gsldrag.F90 are identical to the ones in the NCAR/ccpp-physics repo? What I did, actually now that I remember, was just to copy them over from NCAR/ccpp-physics to my branch of NOAA-GSL/ccpp-physics. So effectively, they are already “merged" into the authoritative repository. Am I getting this right? If not, I’ll cry uncle. :)
> […](#)

No need to cry ;-) they are identical but they are not merged, because a merge would mean that the commit history for these files is identical. In other words, after merging this PR, I would be able to merge ccpp-physics main as a whole and it would recognize that the changes had already been applied. This is not the case here, however, because GitHub doesn't inspect line by line differences and realizes that they are the same. It looks at the commit history. If the hash of a certain commit is not present, then it will try to apply it. Since you already applied it manually (in another commit), it will cause a merge conflict.

**Comment by mdtoy** [comment]
Okay, that makes sense.  Thanks for explaining.

**Comment by DomHeinzeller** [comment]
This PR is not necessary, because the updates will be brought over from the authoritative repositories in PR https://github.com/NOAA-GSL/ccpp-physics/pull/109.

**Pull request closed without merging**
