### PR TITLE
dtend: add drag_suite tendencies and fix many bugs in convection tendencies

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
Fix many bugs in 3D diagnostic tendency code, found by Man Zhang and Sam Trahan.

ufs-weather-model changes: https://github.com/NOAA-GSL/ufs-weather-model/pull/82
fv3atm changes: https://github.com/NOAA-GSL/fv3atm/pull/92

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
~~I just noticed I left some debug prints and commented-out code in the PR. I'll remove it shortly, after recompiling and doing some quick tests.~~

**Comment by SamuelTrahanNOAA** [comment]
> I just noticed I left some debug prints and commented-out code in the PR. I'll remove it shortly, after recompiling and doing some quick tests.

This has been corrected. Also, the error was in fv3atm, not ccpp-physics.

**Comment by SamuelTrahanNOAA** [comment]
Man Zhang is doing an independent test of these changes. They should not be merged until her analysis is complete.

**Review by climbfuji — APPROVED** [review]
Thanks for making these changes. It's getting more complicated and less portable every time, but that's what we have to live with until the CCPP schemes and framework are tidied up.

**Comment by SamuelTrahanNOAA** [comment]
> Thanks for making these changes. It's getting more complicated and less portable every time, but that's what we have to live with until the CCPP schemes and framework are tidied up.

Until the CCPP schemes advertise their tendencies, I have no choice but to duplicate logic several places in the code. There just isn't any other way to get the correct tendencies.

**Pull request merged**
