### PR TITLE
The runoff output is changed from instantaneous to accumulated

### PR DESCRIPTION
**Pull request by tanyasmirnova**
In the RUC LSM driver the output of surface runoff is changed from the instantaneous to accumulated.

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
I think sent this to the wrong repository. Did you mean to use the ufs-community repo instead?

**Comment by tanyasmirnova** [comment]
> I think sent this to the wrong repository. Did you mean to use the ufs-community repo instead?

@SamuelTrahanNOAA Sam, yes I meant the ufs-community repo, but my fork is done from NOAA-GSL repo. Should I remove the fork and do a new fork from ufs-community?

**Comment by SamuelTrahanNOAA** [comment]
> > I think sent this to the wrong repository. Did you mean to use the ufs-community repo instead?
> 
> @SamuelTrahanNOAA Sam, yes I meant the ufs-community repo, but my fork is done from NOAA-GSL repo. Should I remove the fork and do a new fork from ufs-community?

All you need to do is close this PR and open a new PR to the right repository. It doesn't matter where you forked from.

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA Sam, could you please check if my PRs are correct now in all three repos: ccpp-physics, FV3 and ufs-weather-model.

**Comment by SamuelTrahanNOAA** [comment]
It looks right.

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA thank you for checking. This one-line change does not have any impact on model performance, only the RRFSv1 output of runoff variable. I think it could be combined with other PRs.

**Pull request closed without merging**
